apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-recommendation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: recommendation
  template:
    metadata:
      labels:
        app: recommendation
    spec:
      containers:
      - name: recommendation
        image: endingstudyproject.azurecr.io/recommendation-system:latest
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: acr-secret

---
apiVersion: v1
kind: Service
metadata:
  name: recommendation-service
spec:
  selector:
    app: recommendation
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
