version: '3.9'

services:
  mongodb:
    image: mongo
    container_name: mongodb-image
    ports:
      - '27017:27017'
    networks:
      - library-network

  backend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.backend
    container_name: backend-image
    ports:
      - '5000:5000'
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://localhost:27017/library_db
    networks:
      - library-network

  frontend:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.frontend
    container_name: frontend-image
    ports:
      - '3000:3000'
    networks:
      - library-network

  recommendation:
    build:
      context: ..
      dockerfile: deployment/Dockerfile.recommendation
    container_name: recommendation-image
    ports:
      - '8000:8000'
    depends_on:
      - mongodb
    networks:
      - library-network

networks:
  library-network:
    driver: bridge
