AWSTemplateFormatVersion: '2010-09-09'
Description: Template for creating an ECS Cluster

Resources:
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: !Sub '${AWS::StackName}-cluster'
